// <auto-generated />
namespace Assesment.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AssesmentAttributeReadModel_AlterRemove_ChecklistId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AssesmentAttributeReadModel_AlterRemove_ChecklistId));
        
        string IMigrationMetadata.Id
        {
            get { return "201809061421448_AssesmentAttributeReadModel_AlterRemove_ChecklistId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
