// <auto-generated />
namespace Assesment.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AssesmentModuleReadModel_AlterModify_Code : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AssesmentModuleReadModel_AlterModify_Code));
        
        string IMigrationMetadata.Id
        {
            get { return "201809020730454_AssesmentModuleReadModel_AlterModify_Code"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
